name: Générer un AAB Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Consulter le dépôt
        uses: actions/checkout@v4

      - name: Configurer Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Installer Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Projet Init Bubblewrap
        run: |
          mkdir twa
          cd twa
          printf "No\n" | bubblewrap init \
            --manifest=https://bogdanvlad-glitch.github.io/Calculactrice/manifest.json \
            --directory=. \
            --packageId=com.bogdan.wrongcalc \
            --name=WrongCalc \
            --launcherName=WrongCalc \
            --display=standalone \
            --orientation=portrait \
            --themeColor=#000000 \
            --backgroundColor=#000000 \
            --startUrl=https://bogdanvlad-glitch.github.io/Calculactrice/ \
            --iconUrl=https://bogdanvlad-glitch.github.io/Calculactrice/icon-512.png \
            --skipPwaValidation

      - name: Construire AAB
        run: |
          cd twa
          bubblewrap build

      - name: Téléverser les fichiers de compilation
        uses: actions/upload-artifact@v4
        with:
          name: WrongCalc-android-build
          path: |
            twa/*.aab
            twa/*.apk
